no longer use custom_attribute feature
feature(custom_attribute) has been removed from rust.

It does not appear to be needed here, so I just removed the line.

For the record:

error[E0557]: feature has been removed
  --> src/lib.rs:18:12
   |
18 | #![feature(custom_attribute)]
   |            ^^^^^^^^^^^^^^^^ feature has been removed
   |
   = note: removed in favor of `#![register_tool]` and `#![register_attr]`